### ISSUE TITLE
New Features:

### ISSUE THREAD

**Issue by MichaelAllenHardeman** [cforler/Ada-Crypto-Library#11]
I have a project in mind, and I want to use the Ada-Crypto-Library to do most of the heavy lifting, but it's missing a few key features, that I'm planning to add:

- Asymetric RIPEMD-160 based on [this spark implementation.](https://sourceforge.net/p/afp/afp-2009-2/ci/c0ebd3de3f8b9a105dc754344205f8fae75831e5/tree/thys/RIPEMD-160-SPARK/)

- [Base 58 Serialization](https://en.wikipedia.org/wiki/Base58)

I also have two questions about the ECDSA public/private keys that I was hoping someone could answer:

1. I was under the impression ECDSA public keys were derived from a private key. I.E. you generate the private key first, then you generate a public key based on the private key. The implementation seems to suggest the opposite to me:

`procedure Gen_Public_Key( Public_Key : out Public_Key_ECDSA; length : in DB.Bit_Length);`
`procedure Gen_Private_Key(Public_Key : in out Public_Key_ECDSA; Private_Key : out Private_Key_ECDSA);`

As you can see you have a method to generate a public key alone, but the only one that generates private keys takes a public key as input. That seems backwards to me?

2. I know that bitcoin addresses are generated on a specific elliptical curve defined in [secp256k1](https://github.com/bitcoin-core/secp256k1), but how would I use your ECDSA implementation to derive [bitcoin like public and private addresses.](https://en.bitcoin.it/wiki/Technical_background_of_version_1_Bitcoin_addresses) More specifically, which components of your private/public keys map to their process. I think d of ECDSA_S_KEY is the private key? and P of ECDSA_P_KEY has the the 32 byte x and y coordinates? 

for reference:

Public Key
`type ECDSA_P_KEY is record`
`   E : Elliptic_Curve_Zp;`
`   P : EC_Point; --x,y`
`   n : Big_Unsigned;`
`   Q : EC_Point; --x,y`
`end record;`

Private Key
`type ECDSA_S_KEY is record`
`   Q : EC_Point; --x,y`
`   d : Big_Unsigned;`
`end record;`

**Comment by cforler** [comment]
Dear Michael


I am  happy to that you want to use our cryptolib. Beware that the
majority of the code is developed by undergraduates or graduates.
Thus the code quality is not always the best. Thus, there is no warranty
at all.


Regarding to your questions.

 Unfortunately , I have no clue what do you mean by "Asymetric
RIPEMD-160" since RIPEMD-160 is a key less primitive.
It is valid to argue that key less  primitive is equivalent to a
symmetric key primitive where the key is always a bit string that
consists of zeros only.
Thus, RIPEMD-160 belongs to the realm of symmetric crypto. 
Nevertheless, I recommend to use SHA-256 or SHA-512 instead of
RIPEMD-160, if possible.

Note that I welcome the integration of RIPEMD-160 into the
Ada-Crypto-Library. Please, feel free to send me a pull request.

Adding Base58 support would be nice.


2 To be honest, the ECDSA was implemented by a an undergraduate hat want
not be mentioned.

The API of the procedure Gen_Private_Key() is a little bit confusing.

 procedure Gen_Private_Key(
                             Public_Key  : in out Public_Key_ECDSA;
                             Private_Key : out Private_Key_ECDSA) is

It looks like that the input parameter "Public_Key" is  the non-secret
domain parameter G which is then overwritten with the public key  Q=dG.

I highly recommend to rename this procedure.

For further Information I recommend to read FIPS-186-3 B.4.1.
http://csrc.nist.gov/publications/fips/fips186-3/fips_186-3.pdf

I am not familiar with Bitcoin. I recommend to set  The non-secret
domain parameter G by using the
Get_Elliptic_Curve()-Method
(crypto-types-elliptic_curves-zp-database.adb). Then you can call the
Gen_Private_Key() procedure to generate a ECDSA keypair.


Best regards,
Christian

**Comment by MichaelAllenHardeman** [comment]
> I am  happy to that you want to use our cryptolib. Beware that the
majority of the code is developed by undergraduates or graduates.
Thus the code quality is not always the best. Thus, there is no warranty
at all.

I was under the impression this library was a little more mature. I think adding new features here will bog me down then, so I'll work on implementing more of my own project before I add new features here.

**Comment by MichaelAllenHardeman** [comment]
hey,

Sorry for the wait, I've been doing lots of research. I think I just implemented base58 in Ada.
https://github.com/MichaelAllenHardeman/base58_ada

I'd appreciate it if you could look over the code and give me some feedback. I'm not sure if this is fully correct and will handle all cases, but the test runs successfully. 
Since crypto currencies are getting popular, and they use base58, I think it might be useful to you :). Feel free to include it in your project! :+1:

**Comment by MichaelAllenHardeman** [comment]
I take it back, with all the test cases there, I'm sure It handles all cases.
